export const englishQuizArabic: Record<string, string> = {
  "Which sentence is appropriate when you meet someone for the first time?": "أي جملة مناسبة عندما تلتقي بشخص لأول مرة؟",
  "See you yesterday.": "رأيتك أمس. (See you yesterday.)",
  "Nice to meet you.": "تشرفت بلقائك. (Nice to meet you.)",
  "I am sleep.": "أنا نائم. (I am sleep.)",
  "It are good.": "إنه جيد. (It are good.)",
  "How do you ask for someone’s name?": "كيف تسأل عن اسم شخص ما؟",
  "What is your name?": "ما اسمك؟ (What is your name?)",
  "Where name you?": "ما اسمك؟ (Where name you?)",
  "What your name?": "ما اسمك؟ (What your name?)",
  "How name is?": "ما اسمك؟ (How name is?)",
  "Which sentence tells the correct time?": "أي جملة تخبر الوقت بشكل صحيح؟",
  "It is five o’clock.": "الساعة الخامسة. (It is five o’clock.)",
  "It five is clock.": "الساعة الخامسة. (It five is clock.)",
  "Five it are.": "الساعة الخامسة. (Five it are.)",
  "It are five o’clock.": "الساعة الخامسة. (It are five o’clock.)",
  "Which preposition is commonly used with days?": "ما حرف الجر الذي يُستخدم عادةً مع الأيام؟",
  "on": "على (on)",
  "at": "عند (at)",
  "in": "في (in)",
  "from": "من (from)",
  "Choose the correct sentence.": "اختر الجملة الصحيحة.",
  "She has two brothers.": "لديها أخان. (She has two brothers.)",
  "She haves two brothers.": "لديها أخان. (She haves two brothers.)",
  "She have two brothers.": "لديها أخان. (She have two brothers.)",
  "She having two brothers.": "لديها أخان. (She having two brothers.)",
  "Which adjective describes a person who helps others?": "أي صفة تصف شخصًا يساعد الآخرين؟",
  "kind": "لطيف (kind)",
  "noisy": "صاخب (noisy)",
  "empty": "فارغ (empty)",
  "late": "متأخر (late)",
  "She ___ to work at eight every morning.": "هي ___ إلى العمل في الثامنة كل صباح. (She ___ to work at eight every morning.)",
  "goes": "يذهب (goes)",
  "going": "ذاهب (going)",
  "gone": "ذهب (gone)",
  "go": "يذهب (go)",
  "Which sentence describes a regular habit?": "أي جملة تصف عادة منتظمة؟",
  "I studied yesterday.": "درستُ أمس. (I studied yesterday.)",
  "I am studying now.": "أنا أدرس الآن. (I am studying now.)",
  "I drink tea every morning.": "أشرب الشاي كل صباح. (I drink tea every morning.)",
  "I will study tomorrow.": "سأدرس غدًا. (I will study tomorrow.)",
  "Which is a polite way to order food?": "ما هي طريقة مهذبة لطلب الطعام؟",
  "I would like the soup, please.": "أود الحساء من فضلك. (I would like the soup, please.)",
  "Food me.": "أطعمني. (Food me.)",
  "Soup give.": "أعطني الحساء. (Soup give.)",
  "Give me food now.": "أعطني الطعام الآن. (Give me food now.)",
  "Which question asks about price?": "أي سؤال يستفسر عن السعر؟",
  "How many is it?": "كم عددها؟ (How many is it?)",
  "How much is it?": "كم ثمنه؟ (How much is it?)",
  "What time it?": "كم الساعة؟ (What time it?)",
  "Where price?": "أين السعر؟ (Where price?)",
  "What does “Turn left” mean?": "ماذا يعني “Turn left”؟",
  "انعطف يمينًا": "انعطف يمينًا (انعطف يمينًا)",
  "توقف": "توقف (توقف)",
  "انعطف يسارًا": "انعطف يسارًا (انعطف يسارًا)",
  "اعبر الشارع": "اعبر الشارع (اعبر الشارع)",
  "Which phrase asks about a location?": "أي عبارة تسأل عن المكان؟",
  "Who bank?": "من في البنك؟ (Who bank?)",
  "When bank is?": "متى يكون البنك؟ (When bank is?)",
  "Where is the bank?": "أين يقع البنك؟ (Where is the bank?)",
  "Bank do what?": "ماذا يفعل البنك؟ (Bank do what?)",
  "What is the past tense of “go”?": "ما صيغة الماضي للفعل “go”؟",
  "goed": "التصريف الخاطئ للفعل 'go': 'goed' (goed)",
  "went": "ذهب (went)",
  "Yesterday, we ___ a movie.": "أكمل الفراغ: Yesterday, we ___ a movie.",
  "watched": "شاهد (watched)",
  "watching": "يشاهد (watching)",
  "watch": "يشاهد / ساعة يد (watch)",
  "watches": "يشاهد / يراقب (watches)",
  "Which sentence combines a past event with a time expression?": "أي جملة تجمع حدثًا ماضياً مع تعبير زمني؟",
  "I visited the market yesterday.": "زرت السوق أمس. (I visited the market yesterday.)",
  "I visiting market.": "أنا أزور السوق. (I visiting market.)",
  "I visits yesterday.": "زرت أمس. (I visits yesterday.)",
  "I visit the market tomorrow.": "سأزور السوق غدًا. (I visit the market tomorrow.)",
  "Which expression is useful when asking for directions?": "أي عبارة مفيدة عند سؤال عن الاتجاهات؟",
  "Could you tell me how to get there?": "هل يمكنك أن تخبرني كيف أصل إلى هناك؟ (Could you tell me how to get there?)",
  "Tell me your yesterday.": "أخبرني عن يومك البارحة. (Tell me your yesterday.)",
  "I am direction.": "أنا الاتجاه. (I am direction.)",
  "How old the road?": "كم عمر الطريق؟ (How old the road?)",
  "Which word begins with the same sound as “ship”?": "أي كلمة تبدأ بنفس صوت كلمة “ship”؟",
  "chip": "رقاقة (chip)",
  "sip": "رشفة (sip)",
  "shop": "متجر / محل (shop)",
  "cheap": "رخيص (cheap)",
  "Which pair contains two different vowel sounds?": "أي زوج يحتوي على صوتي علة مختلفين؟",
  "ship / sheep": "سفينة / خروف (ship / sheep)",
  "cat / cat": "قطة / قطة (cat / cat)",
  "pen / pen": "قلم / قلم (pen / pen)",
  "book / book": "كتاب / كتاب (book / book)",
  "___ are my friends.": "أكمل الفراغ: ___ are my friends.",
  "She": "هي (She)",
  "They": "هم (They)",
  "It": "هو/هي (It)",
  "He": "هو (He)",
  "Choose the negative sentence.": "اختر الجملة المنفية.",
  "I not am tired.": "أنا لست متعبًا. (I not am tired.)",
  "I am not tired.": "أنا لست متعبًا. (I am not tired.)",
  "I are not tired.": "أنا لست متعبًا. (I are not tired.)",
  "I not tired am.": "أنا لست متعبًا. (I not tired am.)",
  "This is ___ book. I own it.": "أكمل الفراغ: This is ___ book. I own it.",
  "me": "إيَّاي (me)",
  "I": "أنا (I)",
  "mine book": "كتابي (mine book)",
  "my": "خاصتي (my)",
  "Which sentence is correct?": "أي جملة صحيحة؟",
  "This are my keys.": "هذه مفاتيحي (This are my keys.)",
  "These is my keys.": "هذه مفاتيحي (These is my keys.)",
  "These are my keys.": "هذه مفاتيحي (These are my keys.)",
  "These my keys are.": "هذه مفاتيحي (These my keys are.)",
  "___ a sofa in the living room.": "أكمل الفراغ: ___ a sofa in the living room.",
  "There are": "هناك (There are)",
  "There is": "هناك (There is)",
  "They is": "هم (They is)",
  "It are": "هو (It are)",
  "Which sentence describes location correctly?": "أي جملة تصف الموقع بشكل صحيح؟",
  "The lamp on is table.": "المصباح على الطاولة (The lamp on is table.)",
  "The table is lamp.": "الطاولة مصباح (The table is lamp.)",
  "The lamp is on the table.": "المصباح على الطاولة (The lamp is on the table.)",
  "On lamp table.": "على مصباح طاولة (On lamp table.)",
  "Which sentence describes a red shirt?": "أي جملة تصف قميصًا أحمر؟",
  "I am wearing a red shirt.": "أرتدي قميصًا أحمر (I am wearing a red shirt.)",
  "I am wearing a shirt red.": "أنا أرتدي قميصًا أحمر.",
  "I wearing red am shirt.": "أنا أرتدي قميصًا أحمر.",
  "I wear a redly shirt.": "أنا أرتدي قميصًا أحمر.",
  "Which question asks about size?": "أي سؤال يسأل عن المقاس؟",
  "What color do you size?": "ما اللون الذي تقيسه؟",
  "How size is color?": "ما حجم اللون؟",
  "What size do you need?": "ما المقاس الذي تحتاجه؟",
  "Where is size wear?": "أين يُرتدى المقاس؟",
  "Which sentence describes a symptom?": "أي جملة تصف عرضًا؟",
  "I am a headache.": "أعاني من صداع.",
  "I do headache.": "أعاني من صداع.",
  "I headache have am.": "أعاني من صداع.",
  "I have a headache.": "أعاني من صداع.",
  "Which phrase asks for medical help?": "أي عبارة تطلب المساعدة الطبية؟",
  "I need to see a doctor.": "أحتاج أن أرى طبيبًا.",
  "I see need doctor to.": "أحتاج أن أرى طبيبًا.",
  "Doctor I am see.": "أحتاج أن أرى طبيبًا.",
  "Help is doctor?": "هل الطبيب يساعد؟",
  "Which sentence describes rainy weather?": "أي جملة تصف الطقس الممطر؟",
  "It raining is.": "إنها تمطر.",
  "It rain are.": "تمطر.",
  "It is raining.": "إنها تمطر.",
  "It is rain yesterday.": "هطلت الأمطار أمس.",
  "Which season comes after summer?": "أي فصل يأتي بعد الصيف؟",
  "winter": "الشتاء (winter)",
  "autumn": "الخريف (autumn)",
  "spring": "الربيع (spring)",
  "summer": "الصيف (summer)",
  "Choose the correct introduction.": "اختر عبارة التعريف الصحيحة.",
  "My name is Ali, and I live in Baghdad.": "اسمي علي وأعيش في بغداد.",
  "I name Ali live.": "اسمي علي وأعيش.",
  "My is name Ali.": "اسمي علي.",
  "My name Ali and I live Baghdad.": "اسمي علي وأعيش في بغداد.",
  "Which sentence is correct for a daily routine?": "أي جملة صحيحة لوصف روتين يومي؟",
  "She gets up at seven.": "تستيقظ في الساعة السابعة.",
  "She get up at seven.": "تستيقظ في الساعة السابعة.",
  "She getting up seven.": "تستيقظ في الساعة السابعة.",
  "She got up every seven.": "كانت تستيقظ كل يوم في الساعة السابعة.",
  "I ___ visit my family next weekend.": "سأ ___ أزور عائلتي نهاية الأسبوع القادم.",
  "have": "لدي (have)",
  "was": "كان (was)",
  "am going to": "سوف (am going to)",
  "Which sentence expresses a spontaneous decision?": "أي جملة تعبر عن قرار عفوي؟",
  "I helped you yesterday.": "ساعدتك أمس.",
  "I will help you.": "سأساعدك.",
  "I am helping every day.": "أنا أساعد كل يوم.",
  "I was help.": "كنت أساعد.",
  "This book is ___ than that one.": "هذا الكتاب ___ من ذلك.",
  "interesting": "مثير للاهتمام (interesting)",
  "more interesting": "أكثر إثارة للاهتمام (more interesting)",
  "most interesting": "الأكثر إثارة للاهتمام (most interesting)",
  "interest": "اهتمام (interest)",
  "Mount Everest is one of the ___ mountains in the world.": "جبل إيفرست هو واحد من الجبال ___ في العالم.",
  "higher": "أعلى (higher)",
  "highest": "الأعلى (highest)",
  "high": "عالي (high)",
  "most high": "الأكثر ارتفاعًا (most high)",
  "While I was cooking, the phone ___.": "بينما كنت أطبخ، الهاتف ___.",
  "rang": "رنّ (rang)",
  "rings": "يرن (rings)",
  "ring": "يرن (ring)",
  "ringing": "رنين (ringing)",
  "Which sentence uses the past continuous correctly?": "أي جملة تستخدم 'past continuous' بشكل صحيح؟",
  "They was play football.": "كانوا يلعبون كرة القدم (They was play football.)",
  "They playing were.": "كانوا يلعبون (They playing were.)",
  "They were playing football.": "كانوا يلعبون كرة القدم (They were playing football.)",
  "They are played football.": "هم يلعبون كرة القدم (They are played football.)",
  "Have you ___ visited London?": "هل ___ زرت لندن؟ (Have you ___ visited London?)",
  "yesterday": "أمس (yesterday)",
  "last": "الماضي (last)",
  "ago": "منذ (ago)",
  "ever": "على الإطلاق (ever)",
  "She has ___ finished her homework.": "هي ___ أنهت واجبها المنزلي. (She has ___ finished her homework.)",
  "already": "بالفعل (already)",
  "tomorrow": "غدًا (tomorrow)",
  "last week": "الأسبوع الماضي (last week)",
  "A person who designs buildings is an ___.": "الشخص الذي يصمّم المباني هو ___.",
  "accountant": "محاسب (accountant)",
  "actor": "ممثل (actor)",
  "architect": "مهندس معماري (architect)",
  "athlete": "رياضي (athlete)",
  "Which sentence describes a job skill?": "أي جملة تصف مهارة وظيفية؟",
  "I can communicate clearly.": "أستطيع التواصل بوضوح. (I can communicate clearly.)",
  "I am communication yesterday.": "كنت أتواصل أمس. (I am communication yesterday.)",
  "I communicate skill.": "أتواصل بمهارة. (I communicate skill.)",
  "I can clearly yesterday.": "كنت واضحًا أمس. (I can clearly yesterday.)",
  "Which question asks about a train departure?": "أي سؤال يسأل عن موعد مغادرة القطار؟",
  "Where train leaves time?": "أين يغادر القطار؟ (Where train leaves time?)",
  "How train is leave?": "كيف يغادر القطار؟ (How train is leave?)",
  "When does train ticket?": "متى تذكرة القطار؟ (When does train ticket?)",
  "What time does the train leave?": "في أي وقت يغادر القطار؟ (What time does the train leave?)",
  "Which item do you usually need to board an international flight?": "ما الذي تحتاجه عادةً للصعود إلى رحلة دولية؟",
  "pillow only": "وسادة فقط (pillow only)",
  "passport": "جواز سفر (passport)",
  "recipe": "وصفة (recipe)",
  "dictionary only": "قاموس فقط (dictionary only)",
  "Which sentence describes a learning goal?": "أي جملة تصف هدفًا تعليميًا؟",
  "I improve yesterday want.": "أردت التحسن أمس. (I improve yesterday want.)",
  "My English is goal learn.": "هدفي هو تعلم اللغة الإنجليزية. (My English is goal learn.)",
  "I wanting English.": "أريد الإنجليزية. (I wanting English.)",
  "I want to improve my English.": "أريد تحسين لغتي الإنجليزية. (I want to improve my English.)",
  "Which habit supports learning?": "أي عادة تدعم التعلّم؟",
  "Never practicing": "لا أتمرن أبدًا (Never practicing)",
  "Reviewing regularly": "المراجعة بانتظام (Reviewing regularly)",
  "Avoiding feedback": "تجنب التغذية الراجعة (Avoiding feedback)",
  "Forgetting new words": "نسيان كلمات جديدة (Forgetting new words)",
  "Which phrase is suitable for starting a phone call?": "أي عبارة مناسبة لبدء مكالمة هاتفية؟",
  "Hello, may I speak to Mr. Ali?": "مرحبًا، هل أستطيع التحدث إلى السيد علي؟ (Hello, may I speak to Mr. Ali?)",
  "Give Ali now!": "أوصلني إلى علي الآن! (Give Ali now!)",
  "Who phone?": "من على الهاتف؟ (Who phone?)",
  "Speak me Ali.": "وصلني إلى علي. (Speak me Ali.)",
  "What can you say when you cannot hear clearly?": "ماذا تقول عندما لا تسمع بوضوح؟",
  "You repeat me now.": "كرر ذلك لي الآن. (You repeat me now.)",
  "I hear yesterday.": "سمعتُ أمس. (I hear yesterday.)",
  "Could you repeat that, please?": "هل يمكنك تكرار ذلك، من فضلك؟ (Could you repeat that, please?)",
  "Say your phone.": "قل رقم هاتفك. (Say your phone.)",
  "Which verb means to cook food in hot oil?": "أي فعل يعني طهي الطعام في زيت ساخن؟",
  "freeze": "يجمد (freeze)",
  "fry": "يقلي (fry)",
  "pour": "يصب (pour)",
  "peel": "يقشر (peel)",
  "First, ___ the vegetables into small pieces.": "أولًا، ___ الخضروات إلى قطع صغيرة.",
  "chopped": "مقطع (chopped)",
  "chopping": "تقطيع (chopping)",
  "chop": "يقطع (chop)",
  "chops": "يقطع (chops)",
  "Which phrase gives an opinion?": "أي عبارة تعبّر عن رأي؟",
  "My opinion it useful is.": "في رأيي إنه مفيد. (My opinion it useful is.)",
  "I opinion useful.": "أعتقد أنه مفيد. (I opinion useful.)",
  "Opinion yesterday.": "الرأي بالأمس. (Opinion yesterday.)",
  "In my opinion, it is useful.": "في رأيي، إنه مفيد. (In my opinion, it is useful.)",
  "Which is a polite suggestion?": "أي عبارة تُعد اقتراحًا مهذبًا؟",
  "Why don’t we take a break?": "لماذا لا نأخذ استراحة؟ (Why don’t we take a break?)",
  "We take break now!": "لنأخذ استراحة الآن! (We take break now!)",
  "You must break.": "يجب أن تأخذ استراحة. (You must break.)",
  "Take a break you.": "خذ استراحة. (Take a break you.)",
  "Which opening is suitable for a formal email?": "أي تحية مناسبة لبداية بريد إلكتروني رسمي؟",
  "Hey dude!": "يا صاح! (Hey dude!)",
  "Yo!": "أهلاً! (Yo!)",
  "Dear Sir or Madam,": "السيد أو السيدة المحترمون، (Dear Sir or Madam,)",
  "Hello yesterday.": "مرحبًا بالأمس. (Hello yesterday.)",
  "Which phrase is suitable for ending a formal email?": "أي عبارة مناسبة لإنهاء رسالة رسمية عبر البريد الإلكتروني؟",
  "Kind regards,": "مع أطيب التحيات، (Kind regards,)",
  "See ya bro,": "أراك لاحقًا يا أخي، (See ya bro,)",
  "Later maybe,": "ربما لاحقًا، (Later maybe,)",
  "Bye yesterday.": "وداعًا بالأمس. (Bye yesterday.)",
  "Which sentence describes a completed experience?": "أي جملة تصف تجربة مُكتملة؟",
  "I visit two countries yesterday.": "زرت دولتين بالأمس. (I visit two countries yesterday.)",
  "I visiting countries.": "أنا أزور دولًا. (I visiting countries.)",
  "I has visit.": "لقد زرت. (I has visit.)",
  "I have visited two countries.": "لقد زرت دولتين. (I have visited two countries.)",
  "Which phrase helps organize a daily presentation?": "أي عبارة تساعد على تنظيم عرضٍ تقديمي يومي؟",
  "Yesterday, blue, because": "أمس، أزرق، لأن (Yesterday, blue, because)",
  "First, then, finally": "أولاً، ثم، أخيرًا (First, then, finally)",
  "Where, who, under": "أين، من، تحت (Where, who, under)",
  "Never, table, quickly": "أبدًا، طاولة، بسرعة (Never, table, quickly)",
  "Which connector shows the order of events?": "أي أداة ربط تُظهر ترتيب الأحداث؟",
  "Although": "على الرغم من (Although)",
  "Unless": "ما لم (Unless)",
  "However": "مع ذلك (However)",
  "Afterwards": "بعد ذلك (Afterwards)",
  "Which sentence is clearest?": "أي جملة هي الأكثر وضوحًا؟",
  "Arrived called friend after.": "بعد أن وصلت، اتصلت بصديقي. (Arrived called friend after.)",
  "After I arrived, I called my friend.": "بعد أن وصلت، اتصلت بصديقي. (After I arrived, I called my friend.)",
  "I after called arrived.": "اتصلت بعد أن وصلت. (I after called arrived.)",
  "Friend I arrived called.": "وصل الصديق الذي اتصلت به. (Friend I arrived called.)",
  "Which source is usually considered reliable for a news report?": "أي مصدر يُعتبر عادةً موثوقًا لتقرير إخباري؟",
  "An official statement": "بيان رسمي (An official statement)",
  "An unknown rumor": "شائعة مجهولة (An unknown rumor)",
  "An anonymous joke": "نكتة مجهولة (An anonymous joke)",
  "An unverified comment": "تعليق غير مُتحقَّق منه (An unverified comment)",
  "The article says the event ___ place on Monday.": "يذكر المقال أن الحدث ___ يوم الاثنين.",
  "take": "يأخذ (take)",
  "taking": "الأخذ (taking)",
  "took": "أخذ (took)",
  "takes yesterday": "يأخذ أمس (takes yesterday)",
  "Which phrase politely disagrees?": "أي عبارة تُعبر عن اختلاف رأي بأدب؟",
  "You are stupid.": "أنت غبي. (You are stupid.)",
  "I see your point, but I disagree.": "أفهم وجهة نظرك، لكني أختلف. (I see your point, but I disagree.)",
  "No, be quiet.": "لا، اصمت. (No, be quiet.)",
  "Your point is nothing.": "وجهة نظرك لا قيمة لها.",
  "Which phrase keeps a discussion moving?": "أي عبارة تحافظ على استمرار النقاش؟",
  "Stop talking forever.": "توقف عن الكلام نهائياً.",
  "I do not discuss.": "أنا لا أناقش.",
  "Could you explain what you mean?": "هل يمكنك أن تشرح ما تقصده؟",
  "Explain yesterday.": "اشرح كلمة 'yesterday'.",
  "Which section of a CV lists previous jobs?": "أي قسم في السيرة الذاتية يذكر الوظائف السابقة؟",
  "Weather": "الطقس (Weather)",
  "Ingredients": "المكونات (Ingredients)",
  "Directions": "إرشادات (Directions)",
  "Work experience": "الخبرة العملية (Work experience)",
  "Which verb is appropriate in a CV?": "أي فعل مناسب في السيرة الذاتية؟",
  "Managed a team": "أدار فريقًا (Managed a team)",
  "Management a team yesterday": "إدارة فريق أمس (Management a team yesterday)",
  "Manageing team": "إدارة فريق (Manageing team)",
  "Was manage": "كان يُدار (Was manage)",
  "What should a paragraph usually begin with?": "بماذا يجب أن تبدأ الفقرة عادةً؟",
  "A random ending": "نهاية عشوائية (A random ending)",
  "A list of unrelated words": "قائمة كلمات غير مرتبطة (A list of unrelated words)",
  "A topic sentence": "جملة موضوعية (A topic sentence)",
  "A signature only": "توقيع فقط (A signature only)",
  "Which connector adds another idea?": "أي أداة ربط تضيف فكرة أخرى؟",
  "Furthermore": "علاوة على ذلك (Furthermore)",
  "Therefore": "لذلك (Therefore)",
  "Finally": "أخيرًا (Finally)",
  "What does an inference require?": "ما الذي يتطلبه الاستدلال؟",
  "Copying every word": "نسخ كل كلمة (Copying every word)",
  "Ignoring the text": "تجاهل النص (Ignoring the text)",
  "Guessing without evidence": "التخمين بدون دليل (Guessing without evidence)",
  "Using evidence to reach a conclusion": "استخدام الأدلة للوصول إلى استنتاج (Using evidence to reach a conclusion)",
  "If a text says “Sara took an umbrella,” what may we infer?": "إذا قال النص “Sara took an umbrella,” فماذا يمكن أن نستنتج؟",
  "She is at the beach for sure.": "هي على الشاطئ بالتأكيد. (She is at the beach for sure.)",
  "It may be raining.": "قد تمطر. (It may be raining.)",
  "It is certainly summer.": "إنه بالتأكيد الصيف. (It is certainly summer.)",
  "She bought a car.": "اشترت سيارة. (She bought a car.)",
  "Which strategy helps when listening to a conversation?": "أي استراتيجية تساعد عند الاستماع لمحادثة؟",
  "Translating every sound": "ترجمة كل صوت (Translating every sound)",
  "Ignoring the speaker": "تجاهل المتحدث (Ignoring the speaker)",
  "Reading a different topic": "قراءة موضوع مختلف (Reading a different topic)",
  "Listening for key words": "الاستماع للكلمات الرئيسية (Listening for key words)",
  "If someone says “Could you say that again?”, what do they need?": "إذا قال شخص ما “Could you say that again?”، ماذا يحتاج؟",
  "Repetition": "التكرار (Repetition)",
  "A ticket": "تذكرة (A ticket)",
  "Silence": "صمت (Silence)",
  "In “The road was narrow, so only one car could pass,” narrow means ___.": "في “The road was narrow, so only one car could pass,” معنى كلمة narrow هو __.",
  "not wide": "ليس واسعًا (not wide)",
  "very expensive": "باهظ الثمن (very expensive)",
  "extremely long": "طويل للغاية (extremely long)",
  "completely clean": "نظيف تمامًا (completely clean)",
  "Which clue can help you understand an unfamiliar word?": "أي دليل يمكن أن يساعدك على فهم كلمة غير مألوفة؟",
  "The font color only": "لون الخط فقط (The font color only)",
  "The page number only": "رقم الصفحة فقط (The page number only)",
  "The surrounding sentence": "الجملة المحيطة (The surrounding sentence)",
  "Ignoring the context": "تجاهل السياق (Ignoring the context)",
  "Which expression is more formal?": "أي تعبير أكثر رسمية؟",
  "Help me out, mate.": "ساعدني يا صاح. (Help me out, mate.)",
  "I would appreciate your help.": "سأكون ممتنًا لمساعدتك. (I would appreciate your help.)",
  "Give me a hand, dude.": "ساعدني يا رجل. (Give me a hand, dude.)",
  "Help now!": "ساعد الآن! (Help now!)",
  "When speaking to a close friend, which greeting is appropriate?": "عند الحديث مع صديق مقرب، أي تحية مناسبة؟",
  "To whom it may concern": "إلى من يهمه الأمر (To whom it may concern)",
  "Dear Sir or Madam": "السيد أو السيدة المحترم/ة (Dear Sir or Madam)",
  "Hi, how are you?": "مرحبًا، كيف حالك؟ (Hi, how are you?)",
  "I hereby greet you": "أحييك بموجب هذا (I hereby greet you)",
  "Which phrase proposes a solution?": "أي عبارة تقترح حلاً؟",
  "The problem is blue.": "المشكلة زرقاء. (The problem is blue.)",
  "I solved tomorrow.": "حللت غدًا. (I solved tomorrow.)",
  "There is no sentence.": "لا توجد جملة. (There is no sentence.)",
  "We could try a different approach.": "يمكننا تجربة نهج مختلف. (We could try a different approach.)",
  "Which question helps identify the cause of a problem?": "أي سؤال يساعد في تحديد سبب المشكلة؟",
  "What caused the delay?": "ما الذي تسبب في التأخير؟ (What caused the delay?)",
  "Who is the color?": "من هو اللون؟ (Who is the color?)",
  "When problem blue?": "متى المشكلة زرقاء؟ (When problem blue?)",
  "How old is the solution?": "كم عمر الحل؟ (How old is the solution?)",
  "Which phrase introduces the topic of a presentation?": "أي عبارة تقدم موضوع العرض التقديمي؟",
  "Talk today I about.": "أتحدث اليوم أنا عن. (Talk today I about.)",
  "I finish before start.": "أنتهي قبل البدء. (I finish before start.)",
  "Today I’m going to talk about...": "اليوم سأتحدث عن... (Today I’m going to talk about...)",
  "Topic yesterday.": "الموضوع بالأمس. (Topic yesterday.)",
  "Which phrase signals the conclusion?": "أي عبارة تشير إلى الخاتمة؟",
  "To sum up": "لتلخيص (To sum up)",
  "At the beginning": "في البداية (At the beginning)",
  "For example only": "كمثال فقط (For example only)",
  "Meanwhile": "في الأثناء (Meanwhile)",
  "Which skill is important in a communication project?": "ما المهارة المهمة في مشروع تواصل؟",
  "Using unrelated vocabulary": "استخدام مفردات غير مرتبطة (Using unrelated vocabulary)",
  "Avoiding planning": "تجنب التخطيط (Avoiding planning)",
  "Speaking without purpose": "التحدث بلا هدف (Speaking without purpose)",
  "Adapting your message to the audience": "تكييف رسالتك مع الجمهور (Adapting your message to the audience)",
  "Which sentence reports a project result?": "أي جملة تبلغ عن نتيجة المشروع؟",
  "Survey show yesterday agree most.": "أظهر الاستطلاع أمس أن معظم المشاركين اتفقوا. (Survey show yesterday agree most.)",
  "The survey showed that most participants agreed.": "أظهر الاستطلاع أن معظم المشاركين اتفقوا. (The survey showed that most participants agreed.)",
  "Participants is survey.": "المشاركون هو الاستطلاع. (Participants is survey.)",
  "Result showing no.": "النتيجة تُظهر رقمًا. (Result showing no.)",
  "Which style is common in academic writing?": "أي أسلوب شائع في الكتابة الأكاديمية؟",
  "Informal and emotional": "غير رسمي وعاطفي (Informal and emotional)",
  "Full of slang": "مليء بالعامية (Full of slang)",
  "Based only on jokes": "مبني فقط على النكات (Based only on jokes)",
  "Precise and objective": "دقيق وموضوعي (Precise and objective)",
  "Which phrase introduces evidence?": "أي عبارة تقدم دليلاً؟",
  "I feel super that...": "أشعر بسعادة كبيرة أن... (I feel super that...)",
  "The findings indicate that...": "تشير النتائج إلى أن... (The findings indicate that...)",
  "Everybody knows, maybe...": "الجميع يعرف، ربما... (Everybody knows, maybe...)",
  "It is totally cool...": "إنه رائع تمامًا... (It is totally cool...)",
  "What makes evidence strong?": "ما الذي يجعل الدليل قويًا؟",
  "It is relevant and reliable.": "ذو صلة وموثوق به. (It is relevant and reliable.)",
  "It is very long only.": "إنه طويل جدًا فقط. (It is very long only.)",
  "It is anonymous and unsupported.": "إنه مجهول وغير مدعوم. (It is anonymous and unsupported.)",
  "It is repeated without a source.": "يتكرر بدون مصدر. (It is repeated without a source.)",
  "Which phrase introduces a counterargument?": "أي عبارة تقدم حجة مضادة؟",
  "For the first time only": "للمرة الأولى فقط (For the first time only)",
  "In my kitchen": "في مطبخي (In my kitchen)",
  "On the other hand": "من ناحية أخرى (On the other hand)",
  "At exactly noon": "عند الظهر بالضبط (At exactly noon)",
  "Which verb describes an upward trend?": "أي فعل يصف اتجاهًا تصاعديًا؟",
  "declined": "انخفض (declined)",
  "increased": "زاد (increased)",
  "remained stable": "ظل مستقرًا (remained stable)",
  "disappeared": "اختفى (disappeared)",
  "The chart shows a ___ in sales from May to June.": "يُظهر الرسم البياني ___ في المبيعات من مايو إلى يونيو. (The chart shows a ___ in sales from May to June.)",
  "rise significantly was": "ارتفع بشكل كبير كان (rise significantly was)",
  "rising significant": "صاعد مهم (rising significant)",
  "significant rise": "ارتفاع كبير (significant rise)",
  "significantly rose is": "ارتفع بشكل كبير هو (significantly rose is)",
  "Which phrase is suitable for requesting an action in a meeting?": "أي عبارة مناسبة لطلب إجراء في اجتماع؟",
  "Send report now, you!": "أرسل التقرير الآن، أنت! (Send report now, you!)",
  "Report Friday you send?": "تقرير الجمعة أنت ترسل؟ (Report Friday you send?)",
  "You report.": "أنت تُبلغ. (You report.)",
  "Could you send the report by Friday?": "هل يمكنك إرسال التقرير بحلول يوم الجمعة؟ (Could you send the report by Friday?)",
  "Which phrase checks agreement?": "أي عبارة تستخدم للتحقق من الاتفاق؟",
  "Are we all agreed on this?": "هل اتفقنا جميعًا على هذا؟ (Are we all agreed on this?)",
  "Agreement where yesterday?": "اتفاق أين أمس؟ (Agreement where yesterday?)",
  "You agree now because.": "أنت توافق الآن لأن. (You agree now because.)",
  "All are meeting.": "الجميع يجتمع. (All are meeting.)",
  "What can sentence stress change?": "ما الذي يمكن أن يغيّره sentence stress؟",
  "The spelling of every word": "تهجئة كل كلمة",
  "The number of letters": "عدد الحروف",
  "The focus or intended meaning": "التركيز أو المعنى المقصود",
  "The language itself": "اللغة نفسها",
  "Connected speech often means that speakers ___.": "غالبًا ما يعني connected speech أن المتكلمين ___.",
  "link sounds between words": "ربط الأصوات بين الكلمات",
  "pronounce every word separately": "نطق كل كلمة على حدة",
  "stop after every syllable": "التوقف بعد كل مقطع",
  "remove all vowels": "حذف جميع الحروف المتحركة",
  "What is an implicit meaning?": "ما المقصود بالمعنى الضمني؟",
  "A title only": "عنوان فقط",
  "A spelling mistake": "خطأ إملائي",
  "A repeated heading": "عنوان مكرر",
  "A meaning suggested but not stated directly": "معنى يُلمَح إليه لكنه غير مذكور صراحة",
  "Which question helps identify the writer’s attitude?": "أي سؤال يساعد في تحديد موقف الكاتب؟",
  "How many letters are there?": "كم عدد الحروف؟",
  "Is the tone approving, critical, or neutral?": "هل النبرة موافقة أم نقدية أم محايدة؟",
  "What color is the page?": "ما لون الصفحة؟",
  "Where was the paper printed?": "أين طُبع المستند؟",
  "Which opening is suitable for a formal complaint?": "أية بداية مناسبة لشكوى رسمية؟",
  "Your service is awful!!!": "خدمتكم فظيعة!!! (Your service is awful!!!)",
  "Hey, fix this now.": "مرحبًا، أصلح هذا الآن. (Hey, fix this now.)",
  "Complaint yesterday.": "شكوى أمس. (Complaint yesterday.)",
  "I am writing to express my dissatisfaction with...": "أكتب لأعبر عن استيائي من... (I am writing to express my dissatisfaction with...)",
  "Which feature improves a professional proposal?": "ما الخاصية التي تحسّن الاقتراح المهني؟",
  "Unrelated jokes": "نكات غير ذات صلة",
  "Clear objectives and supporting reasons": "أهداف واضحة وأسباب داعمة",
  "Missing dates": "تواريخ مفقودة",
  "Vague promises only": "وعود غامضة فقط",
  "Which sentence discusses a possible effect of AI?": "أي جملة تناقش تأثيرًا محتملاً لـAI؟",
  "AI may transform the way people work.": "قد تُحوّل الذكاء الاصطناعي طريقة عمل الناس. (AI may transform the way people work.)",
  "AI transform yesterday work may.": "الذكاء الاصطناعي يحوّل أمس العمل قد. (AI transform yesterday work may.)",
  "AI is a yesterday.": "الذكاء الاصطناعي هو أمس. (AI is a yesterday.)",
  "Technology no sentence.": "التكنولوجيا ليست جملة. (Technology no sentence.)",
  "What does “data privacy” refer to?": "ماذا يعني مصطلح “data privacy”؟",
  "Making data colorful": "تلوين البيانات",
  "Deleting every computer": "حذف كل جهاز كمبيوتر",
  "Protecting personal information": "حماية المعلومات الشخصية",
  "Sharing passwords publicly": "مشاركة كلمات المرور علنًا",
  "Which answer best supports a claim in an interview?": "أي إجابة تدعم الادعاء بشكل أفضل في مقابلة؟",
  "“I am good” only": "\"I am good\" فقط",
  "A specific example from your experience": "مثال محدد من خبرتك",
  "No answer": "لا إجابة",
  "A completely unrelated story": "قصة غير ذات صلة تمامًا",
  "Which phrase buys time to think?": "أي عبارة تكسبك وقتًا للتفكير؟",
  "I don’t question.": "لا أطرح أسئلة. (I don’t question.)",
  "Ask another yesterday.": "اسأل شخصًا آخر أمس. (Ask another yesterday.)",
  "That’s an interesting question.": "هذا سؤال مثير للاهتمام. (That’s an interesting question.)",
  "Question is finished before.": "انتهى السؤال سابقًا. (Question is finished before.)",
  "Which activity combines reading and writing?": "أي نشاط يجمع بين القراءة والكتابة؟",
  "Listening to music only": "الاستماع إلى الموسيقى فقط (Listening to music only)",
  "Repeating one sound only": "تكرار صوت واحد فقط (Repeating one sound only)",
  "Looking at a picture silently": "النظر إلى صورة بصمت (Looking at a picture silently)",
  "Reading a report and summarizing it": "قراءة تقرير وتلخيصه (Reading a report and summarizing it)",
  "Which plan is measurable?": "أي خطة قابلة للقياس؟",
  "I will write 150 words three times a week.": "سأكتب 150 كلمة ثلاث مرات في الأسبوع. (I will write 150 words three times a week.)",
  "I will improve somehow.": "سأتحسن بطريقة ما. (I will improve somehow.)",
  "I might study one day.": "قد أدرس يومًا ما. (I might study one day.)",
  "I want better English maybe.": "أريد إنجليزية أفضل ربما. (I want better English maybe.)",
  "Which sequence best describes a research project?": "أي تسلسل يصف مشروعًا بحثيًا بشكلٍ أفضل؟",
  "Present, guess, delete, forget": "عرض، تخمين، حذف، نسيان (Present, guess, delete, forget)",
  "Interview only": "مقابلة فقط (Interview only)",
  "Research, interview, analyze, report, present": "البحث، المقابلة، التحليل، التقرير، العرض (Research, interview, analyze, report, present)",
  "Write without collecting information": "الكتابة دون جمع معلومات (Write without collecting information)",
  "Why should a project cite its sources?": "لماذا يجب أن يستشهد المشروع بمصادره؟",
  "To credit information and support credibility": "منح الفضل للمعلومات ودعم المصداقية (To credit information and support credibility)",
  "To make the report longer only": "لجعل التقرير أطول فقط (To make the report longer only)",
  "To hide weak evidence": "لإخفاء الأدلة الضعيفة (To hide weak evidence)",
  "To avoid organizing ideas": "لتجنب تنظيم الأفكار (To avoid organizing ideas)",
  "Which goal follows the SMART approach?": "أي هدف يتبع نهج SMART؟",
  "I will become perfect soon.": "سأصبح مثاليًا قريبًا. (I will become perfect soon.)",
  "I will study more sometime.": "سأدرس أكثر في وقت ما. (I will study more sometime.)",
  "I want to improve everything immediately.": "أريد تحسين كل شيء فورًا. (I want to improve everything immediately.)",
  "I will practice speaking for 20 minutes, four days a week, for one month.": "سأتمرن على التحدث لمدة 20 دقيقة، أربعة أيام في الأسبوع، لمدة شهر. (I will practice speaking for 20 minutes, four days a week, for one month.)",
  "What is a useful next step after completing B2?": "ما هي الخطوة المفيدة التالية بعد إكمال مستوى B2؟",
  "Stop using English completely.": "توقف عن استخدام الإنجليزية تمامًا. (Stop using English completely.)",
  "Identify weaknesses and choose a C1 or certified-exam plan.": "تحديد نقاط الضعف واختيار خطة لمستوى C1 أو خطة لامتحان معتمد. (Identify weaknesses and choose a C1 or certified-exam plan.)",
  "Forget previous feedback.": "تجاهل الملاحظات السابقة. (Forget previous feedback.)",
  "Avoid all challenging texts.": "تجنب كل النصوص الصعبة. (Avoid all challenging texts.)"
};
